FROM node:18-alpine AS base

# Set the working directory in the container to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./


# ---- Dependencies Stage ----
# This stage is only for installing npm dependencies.
FROM base AS dependencies

# Install dependencies. The --only=production flag ensures only necessary packages are installed, skipping devDependencies.
RUN npm install --only=production


# ---- Release Stage ----
# This is the final image we will use.
FROM base AS release

# Set the working directory
WORKDIR /app

# Copy the installed dependencies from the 'dependencies' stage
COPY --from=dependencies /app/node_modules ./node_modules

# Copy the rest of your application code
COPY . .

CMD ["node", "index.js"]